<doc.type.html>
<script>
Filename=CovidStrings2KeyWords.JS
Let Original String=”
Let Word To Add-
Let Updated String {Original String} {Word To Add}
Console Log Updated String
Covid Strings2 Key Word List=[Staying At Home Shorter Than Soda Can On Venus,Rihana,Super Spreader Supra,Sun Cubed,Beer,Pill,Dexie,Fifth Harmonies,Aaron Rodgers Coverup Worse Than Crime, Saturn Astra 
VitaminD,MDX, “One”+”Comedian”+”Believed”+”The”+”Last”+”Year”+”Was”+”One”+”And”+”Four”+”Twenty”+”Firsts”+”Of”+”A”+-“+Year”. 46 To 43 Percent,Bubble Round Robin Format,Vitamin D Exposure Natural ]
String=””
For String In Covid Strings Search Word List
Select Characters
Edit Diffuse Property
Desired Color=Green
Covid Strings2 ReferenceList=[A: Post-Lockdown Anxiety: Types And Coping Techniques (Medicalnewstoday.Com)B: Venus Fact Sheet(Nasa.Gov), C: Remote Work Is Here To Stay And Will Increase Into2023, Experts Say (Forbes.Com), D: Https://Www.Merriam-Webster.Com/Words-At-Play/Super-Spreader-Figurative
E: 2023 Toyota GR Supra Review, Pricing, And Specs (Caranddriver.Com),F: Https://Www.Nytimes.Com/2020/10/07/Us/Politics/Trump-Coronavirus-Blessing.Html,Https://Www.Cbsnews.Com/News/No-Coronas-Beer-Sales-Did-Not-Suffer-From-The-Coronavirus, G: Https://Www.Businessinsider.Com/Elon-Musk-Tweets-Take-The-Red-Pill-What-It-Means-2020-5
H: Dexamethasone Uses, Dosage & Side Effects - Drugs.Com, I: Https://Www.Azlyrics.Com/Lyrics/Fifthharmony/Workfromhome.Html, J: Https://Www.Nbcsports.Com/Chicago/Bears/Did-Aaron-Rodgers-Lie-About-His-Covid-19-Vaccination-Status, K: Https://Www.Consumerreports.Org/Cars/Saturn/Astra/2008/Reliability/, L: How Does Vitamin D Supplementation Impact COVID-19 Vaccine Efficacy? (News-Medical.Net) 
M: Acura MDX | Premium Performance SUV | Acura.Com, N: Https://Www.Cnn.Com/Videos/Media/2021/03/12/Colbert-Late-Night-Pandemic-Anniversary-Orig.Cnn, O: Polls Show How Frustrated Americans Are With Covid Restrictions - The New York Times (Nytimes.Com)
P: Https://Www.Espn.Com/Nba/Story/_/Id/30055011/Everything-Happened-Nba-Bubble, Q: Https://Www.Sportingnews.Com/Us/Nhl/News/Nhl-Stanley-Cup-Playoff-Bracket-Format/Q81rq38mwrwlkelq1ukbqfg9], R: Vitamin D3 And K2 And Their Potential Contribution To Reducing The COVID-19 Mortality Rate- PMC(Nih.Gov)
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
A =Pc.CreateScript(A);
A.Attributes.Add(Foobar, { Type:Entity});
A.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
B=Pc.CreateScript(B);
B.Attributes.Add(Foobar, { Type:Entity});
B.Prototype.Initialize =Function() 
Console.Log(This.Foobar.Name);
Asset This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
C =Pc.CreateScript(C);
C.Attributes.Add(Foobar, { Type:Entity});
C.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
D=Pc.CreateScript(D);
D.Attributes.Add(Foobar, { Type:Entity});
D.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
E =Pc.CreateScript(E);
E.Attributes.Add(Foobar, { Type:Entity});
E.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
F =Pc.CreateScript(F);
F.Attributes.Add(Foobar, { Type:Entity});
F.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
G =Pc.CreateScript(G);
G.Attributes.Add(Foobar, { Type:Entity});
G.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
H =Pc.CreateScript(H);
H.Attributes.Add(Foobar, { Type:Entity});
H.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
I=Pc.CreateScript(I);
I.Attributes.Add(Foobar, { Type:Entity});
I.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
J =Pc.CreateScript(J);
J.Attributes.Add(Foobar, { Type:Entity});
J.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
K=Pc.CreateScript(K);
K.Attributes.Add(Foobar, { Type:Entity});
K.Prototype.Initialize =Function() {
Console.Log(This.Foobar.Name);
Asset= This App.Assets.Find()
Template Asset Resource 
Entity Template Instanite
Entity Script Foobar=This Entity
Entity Reparnet (This.Entity)
L=Pc.CreateScript(L);
l.attributes.add(foobar, {type:entity});
l.prototype.initialize=function() {
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar, {type:entity});
p.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
