doc.type.html
html lang en
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings2’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references 
heading3=script templates
filename=covid strings2 key words.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
<header.html>
keywords
key search words for covid strings2
covid strings2 key word list=[shorter than soda can on venus,rihana,super spreader,sun cubed,beer,pill,dexie,fifth harmonies,aaron rodgers worse than crime, astrazencia saturn,
vitamin d,medical doctors perscription,”one”+”and”+”four”+”twenty”+”firsts,46 to 43 percent,bubble round robin format,vitamin d exposure natural]
string=””
for string in covid strings search word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings2
covid strings2 reference list=[a:post-lockdown anxiety:types and coping techniques (medicalnewstoday.com)b:venus fact sheet(nasa.gov),c:remote work is here to stay and will increase into2023,experts say (forbes.com),d:https://www.merriam-webster.com/words-at-play/super-spreader-figurative
e:2023 toyota gr supra review,pricing,and specs (caranddriver.com),f:https://www.nytimes.com/2020/10/07/us/politics/trump-coronavirus-blessing.html,g:https://www.cbsnews.com/news/no-coronas-beer-sales-did-not-suffer-from-the-coronavirus,h:https://www.businessinsider.com/elon-musk-tweets-take-the-red-pill-what-it-means-2020-5
i:dexamethasone uses,dosage & side effects -drugs.com,j:https://www.azlyrics.com/lyrics/fifthharmony/workfromhome.html,k:https://www.nbcsports.com/chicago/bears/did-aaron-rodgers-lie-about-his-covid-19-vaccination-status,l:https://www.consumerreports.org/cars/saturn/astra/2008/reliability/,m:how does vitamin d supplementation impact covid-19 vaccine efficacy? (news-medical.net) 
n:acura mdx |premium performance suv|acura.com,o:https://www.cnn.com/videos/media/2021/03/12/colbert-late-night-pandemic-anniversary-orig.cnn,p:polls show how frustrated americans are with covid restrictions -the new york times(nytimes.com)
q:https://www.espn.com/nba/story/_/id/30055011/everything-happened-nba-bubble,r:https://www.sportingnews.com/us/nhl/news/nhl-stanley-cup-playoff-bracket-format/Q81rq38mwrwlkelq1ukbqfg9], s:vitamin d3 and k2 and their potential contribution to reducing the covid-19 mortality rate-pmc(nih.gov)
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar, {type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.createscript(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h =pc.createscript(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instanite
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.createscript(j);
j.attributes.add(foobar, {type:entity});
j.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.createscript(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.createscript(l);
l.attributes.add(foobar, {type:entity});
l.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function() 
console.log(this.foobar.name);
asset= this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar, {type:entity});
p.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
s=pc.createscript(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
